### ISSUE TITLE
Warning: Undefined array key "producers" in /vendor\okstuff\phpnsq\src\phpnsq\Conn\Lookupd.php on line 48

### ISSUE THREAD

**Issue by tasaddaq-rana** [cgxxv/phpnsq#13]
ERROR:

Warning: Undefined array key "producers" in C:\xampp6\htdocs\api\vendor\okstuff\phpnsq\src\phpnsq\Conn\Lookupd.php on line 48

Warning: foreach() argument must be of type array|object, null given in C:\xampp6\htdocs\api\vendor\okstuff\phpnsq\src\phpnsq\Conn\Lookupd.php on line 48

Fatal error: Uncaught ValueError: array_rand(): Argument #1 ($array) cannot be empty in C:\xampp6\htdocs\api\vendor\okstuff\phpnsq\src\phpnsq\Conn\Pool.php:50 Stack trace: #0 C:\xampp6\htdocs\api\vendor\okstuff\phpnsq\src\phpnsq\Conn\Pool.php(50): array_rand(Array) #1 C:\xampp6\htdocs\api\vendor\okstuff\phpnsq\src\phpnsq\PhpNsq.php(57): OkStuff\PhpNsq\Conn\Pool->getConn() #2 C:\xampp6\htdocs\api\abc.php(12): OkStuff\PhpNsq\PhpNsq->publish('Hello nsq.') #3 {main} thrown in C:\xampp6\htdocs\api\vendor\okstuff\phpnsq\src\phpnsq\Conn\Pool.php on line 50

My Code is

require __DIR__ . "/vendor/autoload.php";

use OkStuff\PhpNsq\PhpNsq;

$config = require __DIR__ . '/vendor/okstuff/phpnsq/src/config/phpnsq.php';
$phpnsq = new PhpNsq($config);

//normal publish
$msg = $phpnsq->setTopic("sample_topic")->publish("Hello nsq.");
var_dump($msg);
exit();

//defered publish
$msg = $phpnsq->setTopic("sample_topic")->publishDefer("this is a defered message.", 10);
var_dump($msg);

//multiple publish
$messages = [
    "Hello, I am nsq client",
    "There are so many libraries developed by PHP",
    "Oh, no, PHP is not so good and slowly",
];
$msg = $phpnsq->setTopic("sample_topic")->publishMulti(...$messages);
var_dump($msg);

Please help to resolve the issue. Thanks

**Comment by cgxxv** [comment]
Maybe your `nsq lookupd` server is not ready or your `nsq lookupd` server configuration is wrong.
